kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "fx-web.fullname" . }}
  namespace: default
  labels:
    k8s-app: {{ include "fx-web.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ include "fx-web.name" . }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: {{ include "fx-web.name" . }}
    spec:
      containers:
        - name: {{ include "fx-web.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
