kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ include "fx-web.name" . }}
  namespace: default
  labels:
    k8s-app: {{ include "fx-web.name" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "fx-web.name" . }}
              servicePort: 80
