apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/drone"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-pv-claim
  namespace: drone
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
